# @package __global__
_target_: hydra_zen.funcs.zen_processing
_zen_target: atria.core.task_runners._atria_trainer.AtriaTrainer
_zen_exclude:
- hydra
- test_run
- experiment_name
- preprocess_image_size
- image_size
- dir_name_filter
- objective
- noise_schedule
- snr_gamma
- train_batch_size
- eval_batch_size
- gray_to_rgb
- backend
- n_devices
defaults:
# defines the task module which is unconditional diffusion
- override /task_module@task_module: ${oc.env:TASK_MODULE}
# defines the training engine config
- override /engine@training_engine: default_training_engine
# defines the validation engine config
- override /engine@validation_engine: generative_modeling_validation_engine
# defines the visualization engine config
- override /engine@visualization_engine: default_visualization_engine
# defines the test engine config
- override /engine@test_engine: generative_modeling_test_engine
# defines the optimizer
- override /optimizer@training_engine.optimizers: adam
# defines the learning rate scheduler
- override /lr_scheduler@training_engine.lr_schedulers: cosine_annealing_lr
- _self_

task_module:
  objective: ${objective}
  diffusion_steps: 1000
  inference_diffusion_steps: 200
  scheduler: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
  # scheduler: diffusers.schedulers.scheduling_ddim.DDIMScheduler
  noise_schedule: ${noise_schedule}
  snr_gamma: ${snr_gamma}


training_engine:
  max_epochs: 40
  engine_step:
    non_blocking_tensor_conv: true
    with_amp: true
  gradient_config:
    gradient_accumulation_steps: 1
  logging:
    refresh_rate: 10
    profile_time: false
  model_ema_config:
    enabled: true
    momentum: 0.0001
    update_every: 1
  model_checkpoint_config:
    dir: checkpoints
    n_saved: 1
    n_best_saved: 1
    monitored_metric: val/loss
    mode: min
    name_prefix: ''
    save_weights_only: false
    load_weights_only: false
    every_n_steps: 1000
    every_n_epochs: null
    load_best_checkpoint_resume: false
    resume_from_checkpoint: true
    resume_checkpoint_file: null
  test_run: ${test_run}
  optimizers:
    lr: 1.0e-4

test_engine:
  test_run: ${test_run}
  logging:
    refresh_rate: 1
    profile_time: false

validation_engine:
  validate_on_start: false
  validate_every_n_epochs: 9999
  use_ema_for_val: true
  test_run: ${test_run}
  logging:
    refresh_rate: 1
    profile_time: false

visualization_engine:
  visualize_on_start: true
  visualize_every_n_epochs: 0.1
  use_ema_for_visualize: false

output_dir: ./output
seed: 42
deterministic: false
backend: nccl
n_devices: 1
do_train: true
do_validation: false
do_visualization: true
do_test: true

# additional override params that are should go inside _zen_exclude
test_run: false
experiment_name: ???
preprocess_image_size: 1024
image_size: 256
objective: epsilon # one of epsilon, sample, v_prediction
noise_schedule: linear
snr_gamma: null
gray_to_rgb: true
train_batch_size: 128 # the first 4 pretaining models were trained with train_batch_size=32 but its too slow!
eval_batch_size: 64
feature_extraction_batch_size: 64

hydra:
  run:
    dir: "${output_dir}/atria_trainer/\
          ${resolve_dir_name:${data_module.dataset_name}}/\
          ${experiment_name}"
  output_subdir: hydra
  job:
    chdir: false