# @package __global__
_target_: hydra_zen.funcs.zen_processing
_zen_target: atria.core.task_runners._atria_trainer.AtriaTrainer
_zen_exclude:
- hydra
- test_run
- experiment_name
- preprocess_image_size
- image_size
- dir_name_filter
- objective
- noise_schedule
- snr_gamma
- train_batch_size
- eval_batch_size
- gray_to_rgb
- backend
- n_devices
- features_key
defaults:
- latent_diffusion/train_base@_here_
- /engine@feature_extractor_engine: default_feature_extractor_engine
- override /data_module@data_module: ${oc.env:TASK}/${oc.env:DATASET}/override_custom_with_features
- _self_

feature_extractor_engine:
  features_key: ${features_key} # we pre-compute and save kl-f4 features with this name

features_key: ???
