_target_: dp_diffusion.engines.dp_training_step.DPTrainingStep
_partial_: true
grad_scaler: null
output_transform:
  path: atria.core.training.engines.utilities._detach_tensor
  _target_: hydra_zen.funcs.get_obj
non_blocking_tensor_conv: false
with_amp: false
test_run: false
