_target_: atria.core.training.engines.evaluation.ValidationEngine
_partial_: true
defaults:
- _self_
- /engine_step@engine_step: default_validation_step
tb_logger: null
epoch_length: null
outputs_to_running_avg: null
logging:
  _target_: atria.core.training.configs.logging_config.LoggingConfig
  logging_steps: 100
  refresh_rate: 10
  log_gpu_stats: false
  profile_time: false
  log_to_tb: true
metrics: null
metric_logging_prefix: null
test_run: false
use_fixed_batch_iterator: false
validate_every_n_epochs: 1.0
validate_on_start: true
min_train_epochs_for_best: 1
use_ema_for_val: false
