_target_: atria.core.training.engines.evaluation.VisualizationEngine
_partial_: true
defaults:
- _self_
- /engine_step@engine_step: default_visualization_step
tb_logger: null
epoch_length: 1
outputs_to_running_avg: null
logging:
  _target_: atria.core.training.configs.logging_config.LoggingConfig
  logging_steps: 100
  refresh_rate: 10
  log_gpu_stats: false
  profile_time: false
  log_to_tb: true
metrics: null
metric_logging_prefix: null
test_run: false
use_fixed_batch_iterator: false
visualize_every_n_epochs: 1.0
visualize_on_start: false
use_ema_for_visualize: false
