[build-system]
requires = ["setuptools>=60", "setuptools-scm>=8.0", "wheel"]
build-backend = "setuptools.build_meta"  # If not defined, then legacy behavior can happen.

[project]
name = "docsets"
version = "0.0.0"  # REQUIRED, although can be dynamic
description = "docsets is a repository for docsets dataset definitions."
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE.txt"}
keywords = ["torch", "machine-learning", "deep-learning"]
authors = [
    {name = "Saifullah", email = "saifullah.saifullah@dfki.de" }
]
maintainers = [
    {name = "Saifullah", email = "saifullah.saifullah@dfki.de" }
]

# Classifiers help users find your project by categorizing it.
#
# For a list of valid classifiers, see https://pypi.org/classifiers/
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
    "docile-benchmark==0.3.4",
    "editdistance==0.8.1",
    "sacremoses==0.1.1",
]

# [project.optional-dependencies]
# test = ["coverage"]

# [project.urls]
# "Homepage" = "https://github.com/saifullah3396/docsets/"
# "Bug Reports" = "https://github.com/saifullah3396/docsets/"
# "Source" = "https://github.com/saifullah3396/docsets/"

[tool.setuptools.packages.find]
where = ["src"]
include = ["docsets*"]

[tool.setuptools.package-data]
docsets = ["*.txt", "*.yaml"]

[tool.pytest.ini_options]
pythonpath = [
    ".", "src", "tests"
]

[tool.distutils.egg_info]
egg_base = "./"
