_target_: atria.data.data_transforms.advanced.BasicImageAug
key: null
gray_to_rgb: false
rgb_to_bgr: false
rgb_to_gray: false
resize: null
center_crop: null
random_resized_crop: null
normalize: true
random_hflip: false
random_vflip: false
mean:
- 0.485
- 0.456
- 0.406
std:
- 0.229
- 0.224
- 0.225
binarize: false
binarize_threshold: 0.5
to_3_channel_gray: false
image_select: null
decode_image_if_needed: true
