_target_: atria.data.data_transforms.advanced.MultiCrop
key: null
image_size: 224
gray_to_rgb: false
to_pil: false
mean:
- 0.485
- 0.456
- 0.406
std:
- 0.229
- 0.224
- 0.225
global_crops_scale:
- 0.4
- 1.0
local_crops_scale:
- 0.05
- 0.4
local_crops_number: 12
local_crop_size: 96
