_target_: atria.data.data_transforms.advanced.RandAug
key: null
input_size: 224
is_training: true
use_prefetcher: false
no_aug: false
scale: null
ratio: null
hflip: 0.5
vflip: 0.0
color_jitter: 0.4
auto_augment: rand-m9-mstd0.5-inc1
interpolation: bicubic
mean:
- 0.485
- 0.456
- 0.406
std:
- 0.229
- 0.224
- 0.225
re_prob: 0.0
re_mode: const
re_count: 1
re_num_splits: 0
crop_pct: null
tf_preprocessing: false
separate: false
n_augs: 1
fixed_resize: false
