defaults:
# take the defaults from the atria/data_module/hugging_face
- /data_module/huggingface@_here_
- /data_transform@dataset_cacher.preprocess_data_transforms.train.ccpdf_preprocess_transform: ccpdf_preprocess_transform
- /data_transform@dataset_cacher.preprocess_data_transforms.evaluation.ccpdf_preprocess_transform: ccpdf_preprocess_transform
- _self_

dataset_name: docsets.document_classification.ccpdf.CCPDF
dataset_config_name: images_with_ocr
dataset_dir: ${oc.env:DATASET_ROOT_DIR}/ccpdf/CCpdf/
caching_enabled: true
train_dataloader_builder:
  batch_size: 2
evaluation_dataloader_builder:
  batch_size: 2
dataset_cacher:
  num_processes: 32