defaults:
# take the defaults from the atria/data_module/hugging_face
- /data_module/huggingface@_here_
- _self_

dataset_name: docsets.document_classification.rvlcdip.RvlCdip
dataset_config_name: images_with_text
dataset_dir: ${oc.env:DATASET_ROOT_DIR}/rvlcdip
caching_enabled: true
train_dataloader_builder:
  batch_size: 2
evaluation_dataloader_builder:
  batch_size: 2