_target_: atria.core.models.torch_model_builders.diffusers.DiffusersModelBuilder
_partial_: true
model_name: ???
model_task: diffusion
model_cache_dir: null
pretrained: true
convert_bn_to_gn: false
is_frozen: false
required_in_training_step: true
pretrained_checkpoint: null
strict: true
frozen_keys_patterns: null
unfrozen_keys_patterns: null
