_target_: atria.core.metrics.layout.f1_score.f1_score
_partial_: true
output_transform:
  path: atria.core.metrics.layout.output_transforms._layout_token_classification_metrics_output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
