# @package __global__
_target_: hydra_zen.funcs.zen_processing
_zen_target: atria.core.task_runners._atria_trainer.AtriaTrainer
_zen_exclude:
- hydra
- test_run
- experiment_name
- image_size
- dir_name_filter
- objective
- noise_schedule
- snr_gamma
- train_batch_size
- eval_batch_size
- gray_to_rgb
- backend
- n_devices
defaults:
- layout_cond_latent_diffusion/train_base@_here_
- override /data_module@data_module: ${oc.env:TASK}/${oc.env:DATASET}/override_custom
- _self_

task_module:
  # this is the main difference, setting this to false allows vae to compute encodings on the go
  # very expensive for training but good for sampling
  use_precomputed_latents_if_available: False
