_target_: atria.core.models.task_modules.atria_task_module.AtriaTaskModule
_partial_: true
defaults:
- _self_
- /torch_model_builder@torch_model_builder: timm
checkpoint_configs: null
dataset_metadata: null
tb_logger: null
