_target_: atria.models.task_modules.huggingface.HuggingfaceTaskModule
_partial_: true
defaults:
- _self_
- /torch_model_builder@torch_model_builder: transformers
checkpoint_configs: null
dataset_metadata: null
tb_logger: null
