_target_: atria.models.task_modules.autoencoding.image.ImageAutoEncodingModule
_partial_: true
defaults:
- _self_
- /torch_model_builder@torch_model_builder: local
checkpoint_configs: null
dataset_metadata: null
tb_logger: null
input_key: image
loss_type: l2
