_target_: atria.models.task_modules.var_autoencoding.image_gan.ImageVarAutoEncodingGANModule
_partial_: true
defaults:
- _self_
- /torch_model_builder@torch_model_builder: diffusers
checkpoint_configs: null
dataset_metadata: null
tb_logger: null
input_key: image
loss_type: lpips_disc
rec_loss_weight: 1.0
kl_loss_weight: 1.0e-06
disc_start: 10001.0
disc_weight: 0.5
