_target_: atria.models.task_modules.classification.sequence.SequenceClassificationModule
_partial_: true
defaults:
- _self_
- /torch_model_builder@torch_model_builder: transformers
checkpoint: null
load_checkpoint_strict: false
dataset_metadata: null
tb_logger: null
use_bbox: true
use_image: true
